default:
  font: Helvetica
  bold: "{* Bold}"
  mono: Andale Mono
  prechap: "Chapter "
  postchap: ""
  presect: "Section "
  postsect: ""
  dql: "“"
  dqr: "”"
  con: "Contents"
  fig: "Figure "
  tab: "Table "
  indent: "\\qquad"
  thanks: "This is the PDF file for the Pro Git book contents. It is licensed under the Creative Commons Attribution-Non Commercial-Share Alike 3.0 license. I hope you enjoy it, I hope it helps you learn Git, and I hope you'll support Apress and me by purchasing a print copy of the book at Amazon: \\url{http://tinyurl.com/amazonprogit}"
zh:
  langrule: "\\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em\n\\XeTeXlinebreakpenalty=0"
  font: WenQuanYi Micro Hei
  bold: WenQuanYi Micro Hei Mono
  mono: WenQuanYi Micro Hei Mono
  prechap: "第"
  postchap: "章"
  presect: ""
  postsect: "节"
  con: "目录"
  fig: "图 "
  tab: "表 "
  indent: "文"
zh-tw:
  langrule: "\\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em\n\\XeTeXlinebreakpenalty=0"
  font: AR PL UMing TW
  bold: AR PL UKai TW
  mono: AR PL UKai TW
  prechap: "第"
  postchap: "章"
  presect: ""
  postsect: "節"
  dql: "『"
  dqr: "』"
  con: "目錄"
  fig: "圖 "
  tab: "表 "
  indent: "文"
ja:
  langrule: "\\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em\n\\XeTeXlinebreakpenalty=0"
  font: IPAexMincho
  bold: VL PGothic
  mono: VL Gothic
  prechap: "第"
  postchap: "章"
  presect: ""
  postsect: "節"
  dql: "『"
  dqr: "』"
  con: "目次"
  fig: "図"
  tab: "表"
  indent: "あ"
  thanks: "これは､書籍 Pro Git のPDF版です｡クリエイティブ・コモンズ 表示 - 非営利 - 継承 3.0(CC BY-NC-SA 3.0)ライセンスの下に提供されています｡Git を学ぶ際の助けになれば幸いです｡もし役にたったなら､書籍の方もぜひよろしくお願いします｡ \\url{http://tinyurl.com/amazonprogit}\\newline Pro Git 日本語版電子書籍(PDF/EPUB/MOBI)を \\url{http://progit-ja.github.io/} で公開しています｡誤訳の指摘､訳文の改善提案､その他ご意見がありましたら､そちらからお願いいたします｡また､Pro Git 日本語版の翻訳､改善にご尽力いただいた皆さんに､厚く御礼申し上げます｡"
ru:
  prechap: "Глава "
  presect: "Раздел "
  con: "Содержание"
  fig: "Рисунок "
  tab: "Таблица "
  dql: "«"
  dqr: "»"
  langrule: "\\frenchspacing"
  thanks: "Это PDF-версия книги Pro Git. Текст книги находится под лицензией Creative Commons Attribution-Non Commercial-Share Alike 3.0. Надеемся, она вам понравится и поможет изучить Git. Если хотите, можете поддержать автора и Apress, купив бумажную версию книги на английском языке на Amazon: \\url{http://tinyurl.com/amazonprogit}.\\newline На сайте перевода книги на русский язык, расположенного по адресу \\url{https://github.com/GArik/progit/wiki}, можно проверить наличие новых версий книги, оставить сообщение об ошибке в тексте, а также скачать книгу в других форматах."
cs:
  prechap: "Kapitola "
  presect: "Oddíl "
  dql: "„"
  dqr: "“"
  fig: "Obrázek "
  tab: "Tabulka "
fr:
  prechap: "Chapitre "
  presect: "Section "
  fig: "figure "
  tab: "Tableau "
  font: Linux Libertine
  mono: Courier New
  con: "Table des matières"
  langrule: "\\frenchspacing\\usepackage{fontspec}\n\\fontspec[Ligatures={Common}]{Linux Libertine}\n"
  thanks: "Ce fichier PDF est la traduction française du livre Pro Git. Il est publié sous license Creative Commons Attribution-Non Commercial-Share Alike 3.0. J'espère que vous l'apprécierez, qu'il vous permettra d'apprendre à utiliser Git et que vous aiderez Apress en achetant le livre original sur Amazon : \\url{http://tinyurl.com/amazonprogit}"
  dql: "«\\,"
  dqr: "\\,»"
es:
  prechap: "Capítulo "
  presect: "Sección "
  fig: "Figura "
  tab: "Tabla "
  con: "Contenidos "  
mk:
  fig: "Слика"
  con: "Содржина"
  prechap: "Поглавје"
  presect: "Секција"
  dql: "„"
  dqr: "“"
  tab: "Табела"
no-nb:
  dql: "«"
  dqr: "»"
  thanks: "Dette er PDF filen for innholdet til boken Pro Git. Den er lisensiert under Creative Commons Attribution-Non Commercial-Share Alike 3.0 lisensen. Jeg håper du vil ha nytte av den, jeg håper den vil hjelpe deg til å lære Git, og jeg håper du vil støtte Apress og meg ved å kjøpe en kopi av denne boken hos Amazon: \\url{http://tinyurl.com/amazonprogit}"
de:
  langrule: "\\frenchspacing"
  prechap: "Kapitel "
  presect: "Abschnitt "
  fig: "Abbildung "
  tab: "Tabelle "
  con: "Inhaltsverzeichnis"
  dql: "„"
  dqr: "“"
  thanks: "Dies ist die PDF-Datei des Buches „Pro Git“. Es ist lizenziert unter der „Creative Commons Attribution-Non Commercial-Share Alike“-Lizenz. Ich hoffe, es gefällt dir, ich hoffe, es hilft dir, Git zu lernen, und ich hoffe, dass du Apress und mich unterstützt, indem du ein gedrucktes Exemplar des Buches über Amazon bestellst: \\url{http://tinyurl.com/amazonprogit}"
ko:
  langrule: "\\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em\n\\XeTeXlinebreakpenalty=0"
  font: NanumBarunGothic
  bold: "{* Bold}"
  mono: NanumGothicCoding
  prechap: ""
  postchap: "장"
  presect: ""
  postsect: "절"
  indent: " "
  con: "목차"
  fig: "그림"
  tab: "표"
  thanks: "지금 보시는 문서는 책 「Pro Git」의 PDF 파일입니다. 본 문서는 크리에이티브 커먼즈 저작자표시-비영리-동일조건변경허락 3.0 (Creative Commons Attribution-Non Commercial-Share Alike 3.0) 조건에 따라 이용할 수 있습니다. 이 책을 통해 Git을 즐겁게 배울 수 있기를 바랍니다. 출판된 책을 Amazon 웹사이트\\url{http://tinyurl.com/amazonprogit}에서 구입하시면 원저자인 Scott Chacon과 Apress 출판사에게 큰 도움이 됩니다.\\newline도서출판 인사이트를 통해서 한국어판이 2013년 4월 19일에 출판되었습니다. 한국어 번역에 대한 자세한 정보는 \\url{https://github.com/progit/progit/tree/master/ko}에서 확인해 주세요."
be:
  prechap: "Глава "
  presect: "Раздзел "
  con: "Змест"
  fig: "Малюнак "
  tab: "Табліца "
pl:
  prechap: "Rozdział "
  presect: "Dział "
  con: "Spis treści"
  fig: "Rysunek "
  tab: "Tabela "
  indent: "\\qquad"
  thanks: "Jest to plik PDF z zawartością książki Pro Git. Rozpowszechniana jest ona na licencji Creative Commons Attribution-Non Commercial-Share Alike 3.0. Mam nadzieję, że spodoba Ci się, że pomoże nauczyć się Gita, oraz mam nadzieję, że wesprzesz wydawnictwo Apress oraz mnie poprzez kupno papierowej wersji tej książki na Amazon: \\url{http://tinyurl.com/amazonprogit}"
