default:
  font: DejaVu Serif
  mono: DejaVu Sans Mono
  chap: "Chapter "
  sect: "Section "
  fig: "Figure "
  tab: "Table "
zh:
  font: AR PL UMing CN
  fig: "图 "
ja:
  font: Japan
  fig: "図"
  tab: "表"
ru:
  fig: "рисунок "
cs:
  chap: "Kapitola "
  sect: "Oddíl "
  fig: "Obrázek "
  tab: "Tabulka "
